# Site settings
title: Bioinformatics of Infectious Diseases
email: apoon42@uwo.ca
author: Art Poon
description: >- # this means to ignore newlines until "baseurl:"
  Online materials for my undergraduate course.
baseurl: "/BioID" # the subpath of your site, e.g. /blog
url: "http://artpoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: art_poon
github_username:  ArtPoon
github_repo: http://github.com/ArtPoon/BioID

# Build settings
markdown: kramdown
mathjax: true
theme: minima
plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
